# Generated by Django 3.0.6 on 2020-06-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=70)),
                ('message', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(max_length=70)),
            ],
        ),
    ]
