# Generated by Django 3.0.6 on 2020-07-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20200625_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='message',
            new_name='comment',
        ),
    ]
