# Generated by Django 3.0.6 on 2020-06-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategories',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
