# Generated by Django 3.0.6 on 2020-06-05 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu_categories', '0002_menucategories_price'),
        ('menu_tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_categories.MenuCategories')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='menu_tags.MenuTags')),
            ],
        ),
    ]
