# Generated by Django 3.0.6 on 2020-06-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_tags', '0001_initial'),
        ('menu_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='tags',
            field=models.ManyToManyField(blank=True, to='menu_tags.MenuTags'),
        ),
    ]
