# Generated by Django 3.0.6 on 2020-05-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='start',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
